import { Data, IProductInput } from "@/types";
import { toSlug } from "./utils";

const products: IProductInput[] = [
  {
    name: "Áo Thun Dài Tay Slim-fit Nam Nike",
    slug: toSlug("Áo Thun Dài Tay Slim-fit Nam Nike"),
    category: "Áo Thun",
    images: ["/images/p11-1.jpg", "/images/p11-2.jpg"],
    tags: ["Sản phẩm mới"],
    isPublished: true,
    price: 21.8,
    listPrice: 0,
    brand: "Nike",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    countInStock: 11,
    description:
      "Được làm từ các hóa chất an toàn hơn cho sức khỏe con người và môi trường",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Xanh", "Đỏ", "Đen"],
    reviews: [],
  },
  {
    name: "Áo Thun Dài Tay Jerzees Chất Liệu Nặng",
    slug: toSlug("Áo Thun Dài Tay Jerzees Chất Liệu Nặng"),
    category: "Áo Thun",
    images: [
      "/images/p12-1.jpg",
      "/images/p12-2.jpg",
      "/images/p12-3.jpg",
      "/images/p12-4.jpg",
    ],
    tags: ["Nổi bật"],
    isPublished: true,
    price: 23.78,
    listPrice: 0,
    brand: "Jerzees",
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 29,
    countInStock: 12,
    description:
      "Làm từ bông trồng ở Mỹ có nguồn gốc bền vững; Dây đeo vai đến vai; Cổ áo may đôi chỉ; Tay áo may liền; Cổ tay áo có đường may ẩn; Thân áo liền mạch cho diện tích in rộng",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Vàng", "Đỏ", "Đen"],
    reviews: [],
  },
  {
    name: "Áo Thun Dài Tay Nam Jerzees",
    slug: toSlug("Áo Thun Dài Tay Nam Jerzees"),
    category: "Áo Thun",
    brand: "Jerzees",
    images: ["/images/p13-1.jpg", "/images/p13-2.jpg"],
    tags: ["Bán chạy nhất"],
    isPublished: true,
    price: 13.86,
    listPrice: 16.03,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 55,
    countInStock: 13,
    description:
      "Áo thun dài tay Jerzees được làm với công nghệ Dri-Power giúp hút ẩm, giữ bạn mát mẻ và khô ráo suốt cả ngày. Chúng tôi cũng bổ sung cổ áo và tay áo dệt kim để tăng độ bền, cùng với cổ áo phẳng cho sự thoải mái. Nếu bạn đang tìm kiếm một chiếc áo đa năng có thể mặc trong suốt các mùa chuyển tiếp, thì đây chính là lựa chọn hoàn hảo.",
    sizes: ["XL", "XXL"],
    colors: ["Xanh", "Trắng"],
    reviews: [],
  },
  {
    name: "Áo Thun Dài Tay Nam Decrum - Áo V-Cổ Thời Trang Mềm Mại, Áo Jersey Tay Dài",
    slug: toSlug(
      "Áo Thun Dài Tay Nam Decrum - Áo V-Cổ Thời Trang Mềm Mại, Áo Jersey Tay Dài"
    ),
    category: "Áo Thun",
    brand: "Jerzees",
    images: ["/images/p14-1.jpg", "/images/p14-2.jpg"],
    tags: ["Khuyến mãi hôm nay"],
    isPublished: true,
    price: 26.95,
    listPrice: 46.03,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 14,
    description:
      "Nâng cấp trang phục của bạn với chiếc áo thun dài tay mềm mại này. Áo tay dài này là sự nâng cấp tuyệt vời từ chiếc áo thun cotton thông thường.",
    sizes: ["XL", "XXL"],
    colors: ["Vàng", "Trắng"],
    reviews: [],
  },
  {
    name: "Áo Thun Nam Muscle Cmdr Slim Fit Henley Dài & Ngắn Tay, Cổ Áo 3 Nút Kim Loại, Áo Thun Thời Trang",
    slug: toSlug(
      "Áo Thun Nam Muscle Cmdr Slim Fit Henley Dài & Ngắn Tay, Cổ Áo 3 Nút Kim Loại, Áo Thun Thời Trang"
    ),
    category: "Áo Thun",
    brand: "Muscle Cmdr",
    images: ["/images/p15-1.jpg", "/images/p15-2.jpg"],
    tags: ["Mới về", "Nổi bật"],
    isPublished: true,
    price: 29.99,
    listPrice: 35.99,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 15,
    description:
      "Thiết kế Slim Fit: Áo Henley Slim Fit của Muscle Cmdr được thiết kế ôm sát cơ thể, làm nổi bật cơ bắp và tạo dáng hình thanh thoát, hoàn hảo cho mọi dịp.",
    sizes: ["XL", "XXL"],
    colors: ["Xanh", "Vàng"],
    reviews: [],
  },
  {
    name: "Áo Thun Dài Tay Nam Hanes Beefy Henley",
    slug: toSlug("Áo Thun Dài Tay Nam Hanes Beefy Henley"),
    category: "Áo Thun",
    brand: "Jerzees",
    images: ["/images/p16-1.jpg", "/images/p16-2.jpg"],
    tags: ["Bán chạy nhất", "Khuyến mãi hôm nay"],
    isPublished: true,
    price: 25.3,
    listPrice: 32.99,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 16,
    numSales: 56,
    description:
      "Vải cotton dày (Heathers là 60% cotton/40% polyester; Pebblestone là 75% cotton/25% polyester)",
    sizes: ["XL", "XXL"],
    colors: ["Xám", "Trắng"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Silver Jeans Co. Jace Slim Fit Bootcut",
    slug: toSlug("Quần Jean Nam Silver Jeans Co. Jace Slim Fit Bootcut"),
    category: "Quần Jean",
    brand: "Silver Jeans Co",
    images: ["/images/p21-1.jpg", "/images/p21-2.jpg"],
    tags: ["Mới về"],
    isPublished: true,
    price: 95.34,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 54,
    numSales: 21,
    description:
      "Quần Jean Nam Silver Jeans Co. Jace Slim Fit Bootcut - Quần Jace là một mẫu quần jean hiện đại dành cho cao bồi. Quần ngồi dưới eo, ôm sát qua hông và đùi. Được hoàn thiện với phần ống quần bootcut dài 18 inch, phù hợp với dáng người thon gọn nhưng vẫn vừa vặn với ủng.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Xanh", "Xám"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Levi's 505 Regular Fit (Cũng có sẵn cho Big & Tall)",
    slug: toSlug(
      "Quần Jean Nam Levi's 505 Regular Fit (Cũng có sẵn cho Big & Tall)"
    ),
    category: "Quần Jean",
    brand: "Levi's",
    images: ["/images/p22-1.jpg", "/images/p22-2.jpg"],
    tags: ["Nổi bật"],
    isPublished: true,
    price: 59.99,
    listPrice: 69.99,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 22,
    numSales: 54,
    description:
      "Một chiếc quần cổ điển thực sự, 505 được thiết kế để có vẻ ngoài và phong cách thoải mái.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Xanh", "Xám"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Essentials Straight-Fit Stretch",
    slug: toSlug("Quần Jean Nam Essentials Straight-Fit Stretch"),
    category: "Quần Jean",
    brand: "Essentials",
    images: ["/images/p23-1.jpg", "/images/p23-2.jpg"],
    tags: ["Bán chạy nhất"],
    isPublished: true,
    price: 38.9,
    listPrice: 45,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 23,
    numSales: 54,
    description:
      "Những chiếc quần jean 5 túi cổ điển này được làm từ vải có chút độ co giãn để mang lại sự thoải mái và giúp duy trì hình dáng của chúng.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Xám", "Xanh"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Buffalo David Bitton Driven Relaxed Denim",
    slug: toSlug("Quần Jean Nam Buffalo David Bitton Driven Relaxed Denim"),
    category: "Quần Jean",
    brand: "Buffalo David Bitton",
    images: ["/images/p24-1.jpg", "/images/p24-2.jpg"],
    tags: ["Khuyến mãi hôm nay"],
    isPublished: true,
    price: 69.99,
    listPrice: 100,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 24,
    numSales: 53,
    description:
      "Quần jean denim tái chế co giãn với màu xanh wash tự nhiên và được mài. Đặc điểm gồm thắt lưng thấp thoải mái và kiểu dáng suông. Vẻ ngoài mài mòn mang lại cảm giác đã sử dụng lâu dài. Logo thân thiện với môi trường màu nâu đỏ được gắn ở thắt lưng phía sau. Hình ảnh lá phong đặc trưng được đục nổi ở khóa kéo.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Xanh", "Xám"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Dickies Relaxed Fit Carpenter",
    slug: toSlug("Quần Jean Nam Dickies Relaxed Fit Carpenter"),
    category: "Quần Jean",
    brand: "Dickies",
    images: ["/images/p25-1.jpg", "/images/p25-2.jpg"],
    tags: ["Hàng mới", "Nổi bật"],
    isPublished: true,
    price: 95.34,
    listPrice: 0,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 25,
    numSales: 48,
    description:
      "Quần jean làm việc thoải mái với các túi kiểu thợ mộc truyền thống và logo ở túi sau.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Xanh", "Xám"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Wrangler Premium Performance Cowboy Cut Slim Fit",
    slug: toSlug(
      "Quần Jean Nam Wrangler Premium Performance Cowboy Cut Slim Fit"
    ),
    category: "Quần Jean",
    brand: "Wrangler",
    images: ["/images/p26-1.jpg", "/images/p26-2.jpg"],
    tags: ["Bán chạy nhất", "khuyến mãi hôm nay"],
    isPublished: true,
    price: 81.78,
    listPrice: 149.99,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 26,
    numSales: 48,
    description:
      "Được thiết kế với độ vừa vặn chức năng, chiếc quần này được làm để mặc cùng với đôi bốt yêu thích của bạn. Được cấu tạo với dáng ôm vừa vặn ở eo, mông và đùi, chiếc quần này mang lại sự thoải mái và chức năng cho những ngày dài trên yên ngựa.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Xanh", "Xám"],
    reviews: [],
  },
  {
    name: "Đồng hồ nam Seiko với mặt đồng hồ đen",
    slug: toSlug("Đồng hồ nam Seiko với mặt đồng hồ đen"),
    category: "Đồng hồ đeo tay",
    brand: "Seiko",
    images: ["/images/p31-1.jpg", "/images/p31-2.jpg"],
    tags: ["Sản phẩm mới"],
    isPublished: true,
    price: 530.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 31,
    numSales: 48,
    description:
      "Vỏ đồng hồ: Vỏ làm bằng thép không gỉ, hình dáng vỏ: tròn, màu sắc vỏ: bạc, Kính: Hardlex, Loại khóa: Khóa gập với an toàn.",
    sizes: [],
    colors: [],
    reviews: [],
  },
  {
    name: "Đồng hồ tự động SEIKO 5 Sport SRPJ83 mặt số màu be, dây nylon, màu be",
    slug: toSlug(
      "Đồng hồ tự động SEIKO 5 Sport SRPJ83 mặt số màu be, dây nylon, màu be"
    ),
    category: "Đồng hồ đeo tay",
    brand: "Seiko",
    images: ["/images/p32-1.jpg", "/images/p32-2.jpg"],
    tags: ["Nổi bật"],
    isPublished: true,
    price: 375.83,
    listPrice: 400,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 32,
    numSales: 48,
    description:
      "Bộ sưu tập Seiko 5 Sport lấy cảm hứng từ kiểu dáng cổ điển của đồng hồ trường/máy bay: Tự động với khả năng lên cót tay.",
    sizes: [],
    colors: [],
    reviews: [],
  },
  {
    name: "Đồng hồ Casio nam mặt kim loại thép không gỉ dây đeo, màu bạc, đồng hồ thể thao 42mm",
    slug: toSlug(
      "Đồng hồ Casio nam mặt kim loại thép không gỉ dây đeo, màu bạc, đồng hồ thể thao 42mm"
    ),
    category: "Đồng hồ đeo tay",
    brand: "Casio",
    images: ["/images/p33-1.jpg", "/images/p33-2.jpg"],
    tags: ["Bán chạy nhất"],
    isPublished: true,
    price: 60.78,
    listPrice: 0,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 33,
    numSales: 48,
    description:
      "Dòng đồng hồ Casio đang phát triển với mẫu MWA-100H-1AVEF này. Với vỏ thép không gỉ có hoàn thiện chải xước, đồng hồ sẽ dễ dàng chịu được tất cả các va đập của cuộc sống hàng ngày.",
    sizes: [],
    colors: [],
    reviews: [],
  },
  {
    name: "Đồng hồ Casio cổ điển vỏ thép không gỉ màu bạc, đồng hồ chỉ ngày",
    slug: toSlug(
      "Đồng hồ Casio cổ điển vỏ thép không gỉ màu bạc, đồng hồ chỉ ngày"
    ),
    category: "Đồng hồ đeo tay",
    brand: "Casio",
    images: ["/images/p34-1.jpg", "/images/p34-2.jpg"],
    tags: ["Khuyến mãi hôm nay"],
    isPublished: true,
    price: 34.22,
    listPrice: 54.99,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 34,
    numSales: 48,
    description:
      "Mẫu đồng hồ MTPVD01D-7EV mới có khả năng chống nước 50m, vỏ thép không gỉ và mặt đồng hồ trắng. Đồng hồ 3 kim, hiển thị ngày này là lựa chọn hoàn hảo cho mọi môi trường.",
    sizes: [],
    colors: [],
    reviews: [],
  },
  {
    name: "Đồng hồ Fossil nam Grant vỏ thép không gỉ, đồng hồ chronograph",
    slug: toSlug(
      "Đồng hồ Fossil nam Grant vỏ thép không gỉ, đồng hồ chronograph"
    ),
    category: "Đồng hồ đeo tay",
    brand: "Fossil",
    images: ["/images/p35-1.jpg", "/images/p35-2.jpg"],
    tags: ["Sản phẩm mới", "Nổi bật"],
    isPublished: true,
    price: 171.22,
    listPrice: 225,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 35,
    numSales: 48,
    description:
      "Đồng hồ chronograph với vỏ màu bạc và xanh, mặt đồng hồ màu xanh ánh kim và chỉ số số La Mã màu bạc.",
    sizes: [],
    colors: ["Xanh", "Đen", "Bạc"],
    reviews: [],
  },
  {
    name: "Đồng hồ Fossil nam Machine vỏ thép không gỉ, đồng hồ quartz",
    slug: toSlug("Đồng hồ Fossil nam Machine vỏ thép không gỉ, đồng hồ quartz"),
    category: "Đồng hồ đeo tay",
    brand: "Fossil",
    images: ["/images/p36-1.jpg", "/images/p36-2.jpg"],
    tags: ["Bán chạy nhất", "Khuyến mãi hôm nay"],
    isPublished: true,
    price: 158.21,
    listPrice: 229.0,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 36,
    numSales: 49,
    description:
      "Với phong cách nam tính màu đen trên đen, đồng hồ Machine lấy cảm hứng từ công nghiệp sẽ tạo thêm điểm nhấn hiện đại cho vẻ ngoài giản dị của bạn. Đồng hồ này còn có chuyển động ba kim trên dây đeo thép không gỉ.",
    sizes: [],
    colors: ["Nâu", "Bạc", "Đen"],
    reviews: [],
  },
  {
    name: "Giày đào tạo nam adidas Grand Court 2.0",
    slug: toSlug("Giày đào tạo nam adidas Grand Court 2.0"),
    category: "Giày",
    brand: "adidas",
    images: ["/images/p41-1.jpg", "/images/p41-2.jpg"],
    tags: ["Hàng mới"],
    isPublished: true,
    price: 81.99,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 41,
    numSales: 48,
    description:
      "Lót giày Cloudfoam Comfort cực kỳ mềm mại và bồng bềnh, với hai lớp đệm được phủ bởi lưới mềm, thoáng khí",
    sizes: ["8", "9", "10"],
    colors: ["Trắng", "Đen", "Xám"],
    reviews: [],
  },
  {
    name: "Giày chạy bộ nam ziitop, giày thể thao thời trang, giày oxford công sở, giày thể thao nhẹ, thoáng khí",
    slug: toSlug(
      "Giày chạy bộ nam ziitop, giày thể thao thời trang, giày oxford công sở, giày thể thao nhẹ, thoáng khí"
    ),
    category: "Giày",
    brand: "ziitop",
    images: ["/images/p42-1.jpg", "/images/p42-2.jpg"],
    tags: ["Nổi bật"],
    isPublished: true,
    price: 39.97,
    listPrice: 49.96,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 42,
    numSales: 50,
    description:
      "Lót giày Cloudfoam Comfort cực kỳ mềm mại và bồng bềnh, với hai lớp đệm được phủ bởi lưới mềm, thoáng khí",
    sizes: ["8", "9", "10"],
    colors: ["Beige", "Đen", "Xám"],
    reviews: [],
  },
  {
    name: "Giày nam Skechers Summits High Range Hands Free Slip-in",
    slug: toSlug("Giày nam Skechers Summits High Range Hands Free Slip-in"),
    category: "Giày",
    brand: "Skechers",
    images: ["/images/p43-1.jpg", "/images/p43-2.jpg"],
    tags: ["Bán chạy nhất"],
    isPublished: true,
    price: 99.99,
    listPrice: 0,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 43,
    numSales: 72,
    description:
      "Bước vào sự thoải mái dễ dàng với Skechers Hands Free Slip-ins™: Summits - High Range. Cùng với Exclusive Heel Pillow™ giúp giữ chân bạn chắc chắn, kiểu dáng này có phần gót giày mô phỏng nổi Skechers Slip-ins™ và lớp vải lưới trên cùng với dây giày cố định",
    sizes: ["8", "9", "10"],
    colors: ["Xanh biển", "Đen", "Xám"],
    reviews: [],
  },
  {
    name: "Giày chạy bộ DLWKIPV nam, giày thể thao, giày đi bộ ngoài trời, giày chạy nhẹ, linh hoạt, thoải mái, thoáng khí",
    slug: toSlug(
      "Giày chạy bộ DLWKIPV nam, giày thể thao, giày đi bộ ngoài trời, giày chạy nhẹ, linh hoạt, thoải mái, thoáng khí"
    ),
    category: "Giày",
    brand: "DLWKIPV",
    images: ["/images/p44-1.jpg", "/images/p44-2.jpg"],
    tags: ["Ưu đãi hôm nay"],
    isPublished: true,
    price: 36.99,
    listPrice: 56.9,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 44,
    numSales: 72,
    description:
      "Thiết kế: Lưới phía trên, thông thoáng. Đế chống trượt, giảm chấn và chống trượt. Bên trong giày rộng và mềm, mang đến cảm giác thoải mái",
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["Nâu", "Đen", "Xám"],
    reviews: [],
  },
  {
    name: "Giày chạy bộ nam ASICS GT-2000 13",
    slug: toSlug("Giày chạy bộ nam ASICS GT-2000 13"),
    category: "Giày",
    brand: "ASICS",
    images: ["/images/p45-1.jpg", "/images/p45-2.jpg"],
    tags: ["Hàng mới", "Nổi bật"],
    isPublished: true,
    price: 179.95,
    listPrice: 200,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 45,
    numSales: 64,
    description:
      "Ít nhất 50% vật liệu chính của giày được làm từ nguyên liệu tái chế để giảm lãng phí và khí thải carbon",
    sizes: ["8", "9", "10", "11"],
    colors: ["Xanh dương", "Đen", "Xám"],
    reviews: [],
  },
  {
    name: "Giày Wearbreeze nam, Urban - Giày siêu thoải mái, Giày Mesh thời trang cho nam",
    slug: toSlug(
      "Giày Wearbreeze nam, Urban - Giày siêu thoải mái, Giày Mesh thời trang cho nam"
    ),
    category: "Giày",
    brand: "Generic",
    images: ["/images/p46-1.jpg", "/images/p46-2.jpg"],
    tags: ["Bán chạy nhất", "Ưu đãi hôm nay"],
    isPublished: true,
    price: 32.99,
    listPrice: 80,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 46,
    numSales: 48,
    description:
      "Lót giày Cloudfoam Comfort cực kỳ mềm mại và bồng bềnh, với hai lớp đệm được phủ bởi lưới mềm, thoáng khí",
    sizes: ["8", "9", "10", "11"],
    colors: ["Xanh lá", "Đen", "Xám"],
    reviews: [],
  },
];

const data: Data = {
  products,
  headerMenus: [
    {
      name: "Khuyến mãi hôm nay",
      href: "/search?tag=todays-deal",
    },
    {
      name: "Sản phẩm mới",
      href: "/search?tag=new-arrival",
    },
    {
      name: "Sản phẩm nổi bật",
      href: "/search?tag=featured",
    },
    {
      name: "Bán chạy nhất",
      href: "/search?tag=best-seller",
    },
    {
      name: "Lịch sử duyệt",
      href: "/#browsing-history",
    },
    {
      name: "Dịch vụ khách hàng",
      href: "/page/customer-service",
    },
    {
      name: "Về chúng tôi",
      href: "/page/about-us",
    },
    {
      name: "Trợ giúp",
      href: "/page/help",
    },
  ],
  carousels: [
    {
      title: "Giày Bán Chạy Nhất",
      buttonCaption: "Mua Ngay",
      image: "/images/banner3.jpg",
      url: "/search?category=Shoes",
      isPublished: true,
    },
    {
      title: "Áo Thun Bán Chạy Nhất",
      buttonCaption: "Mua Ngay",
      image: "/images/banner1.jpg",
      url: "/search?category=T-Shirts",
      isPublished: true,
    },
    {
      title: "Ưu Đãi Tốt Nhất Về Đồng Hồ Đeo Tay",
      buttonCaption: "Xem Thêm",
      image: "/images/banner2.jpg",
      url: "/search?category=Wrist Watches",
      isPublished: true,
    },
  ],
};

export default data;
