import { Data, IProductInput, IUserInput } from "@/types";
import { toSlug } from "./utils";
import bcrypt from "bcryptjs";

const users: IUserInput[] = [
  {
    name: "Trần Tuấn Kiệt",
    email: "admin@gmail.com",
    password: bcrypt.hashSync("123456", 5),
    role: "Admin",
    address: {
      fullName: "Nguyễn Văn A",
      street: "234 Đường Trần Văn Voi",
      city: "Sa Đéc",
      province: "Đồng Tháp",
      postalCode: "81000",
      country: "Việt Nam",
      phone: "0901234567",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Trần Thị B",
    email: "tranthi.b@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Trần Thị B",
      street: "222 Đường Trường Chinh",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-234-5678",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Lê Văn C",
    email: "levan.c@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Lê Văn C",
      street: "333 Đường Giải Phóng",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-345-6789",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Phạm Thị D",
    email: "phamthi.d@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Phạm Thị D",
      street: "444 Đường Cầu Giấy",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Hoàng Văn E",
    email: "hoangvan.e@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Hoàng Văn E",
      street: "555 Đường Nguyễn Trãi",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-567-8901",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Nguyễn Thị F",
    email: "nguyenthif@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Nguyễn Thị F",
      street: "666 Đường Kim Mã",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-678-9012",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Lý Văn G",
    email: "lyvang@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Lý Văn G",
      street: "777 Đường Phạm Văn Đồng",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-789-0123",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Phan Văn H",
    email: "phanvan.h@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Phan Văn H",
      street: "888 Đường Hoàng Quốc Việt",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-890-1234",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Đinh Thị I",
    email: "dinhthi.i@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Đinh Thị I",
      street: "999 Đường Lạc Long Quân",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-901-2345",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Ngô Văn J",
    email: "ngovan.j@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Ngô Văn J",
      street: "101 Đường Bưởi",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-012-3456",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Phùng Thị K",
    email: "phungthi.k@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Phùng Thị K",
      street: "102 Đường Văn Cao",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-123-4567",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Nguyễn Văn L",
    email: "nguyenvan.l@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Nguyễn Văn L",
      street: "103 Đường Xuân Thủy",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-234-5678",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Vũ Thị M",
    email: "vuthi.m@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Vũ Thị M",
      street: "104 Đường Phạm Hùng",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-345-6789",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Trịnh Văn N",
    email: "trinhvan.n@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Trịnh Văn N",
      street: "105 Đường Nguyễn Phong Sắc",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Bùi Thị O",
    email: "buithi.o@example.vn",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Bùi Thị O",
      street: "106 Đường Hồ Tùng Mậu",
      city: "Hà Nội",
      province: "Hà Nội",
      postalCode: "100000",
      country: "Việt Nam",
      phone: "090-567-8901",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
];

const products: IProductInput[] = [
  {
    name: "Áo Thun Dài Tay Slim-fit Nam Nike",
    slug: toSlug("Nike Mens Slim-fit Long-Sleeve T-Shirt"),
    category: "T-Shirts",
    images: ["/images/p11-1.jpg", "/images/p11-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 21.8,
    listPrice: 0,
    brand: "Nike",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    countInStock: 11,
    description:
      "Được làm từ các hóa chất an toàn hơn cho sức khỏe con người và môi trường",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Red", "Black"],
    reviews: [],
  },
  {
    name: "Áo Thun Dài Tay Jerzees Chất Liệu Nặng",
    slug: toSlug("Jerzees Long-Sleeve Heavyweight Blend T-Shirt"),
    category: "T-Shirts",
    images: [
      "/images/p12-1.jpg",
      "/images/p12-2.jpg",
      "/images/p12-3.jpg",
      "/images/p12-4.jpg",
    ],
    tags: ["featured"],
    isPublished: true,
    price: 23.78,
    listPrice: 0,
    brand: "Jerzees",
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 29,
    countInStock: 12,
    description:
      "Làm từ bông trồng ở Mỹ có nguồn gốc bền vững; Dây đeo vai đến vai; Cổ áo may đôi chỉ; Tay áo may liền; Cổ tay áo có đường may ẩn; Thân áo liền mạch cho diện tích in rộng",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Yellow", "Red", "Black"],
    reviews: [],
  },
  {
    name: "Áo Thun Dài Tay Nam Jerzees",
    slug: toSlug("Jerzees Men Long-Sleeve T-Shirt"),
    category: "T-Shirts",
    brand: "Jerzees",
    images: ["/images/p13-1.jpg", "/images/p13-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 13.86,
    listPrice: 16.03,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 55,
    countInStock: 13,
    description:
      "Áo thun dài tay Jerzees được làm với công nghệ Dri-Power giúp hút ẩm, giữ bạn mát mẻ và khô ráo suốt cả ngày. Chúng tôi cũng bổ sung cổ áo và tay áo dệt kim để tăng độ bền, cùng với cổ áo phẳng cho sự thoải mái. Nếu bạn đang tìm kiếm một chiếc áo đa năng có thể mặc trong suốt các mùa chuyển tiếp, thì đây chính là lựa chọn hoàn hảo.",
    sizes: ["XL", "XXL"],
    colors: ["Blue", "White"],
    reviews: [],
  },
  {
    name: "Áo Thun Dài Tay Nam Decrum - Áo V-Cổ Thời Trang Mềm Mại, Áo Jersey Tay Dài",
    slug: toSlug(
      "Decrum Mens Plain Long Sleeve T-Shirt - Comfortable Soft Fashion V Neck Full Sleeves Jersey Shirts"
    ),
    category: "T-Shirts",
    brand: "Jerzees",
    images: ["/images/p14-1.jpg", "/images/p14-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 26.95,
    listPrice: 46.03,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 14,
    description:
      "Nâng cấp trang phục của bạn với chiếc áo thun dài tay mềm mại này. Áo tay dài này là sự nâng cấp tuyệt vời từ chiếc áo thun cotton thông thường.",
    sizes: ["XL", "XXL"],
    colors: ["Yellow", "White"],
    reviews: [],
  },
  {
    name: "Áo Thun Nam Muscle Cmdr Slim Fit Henley Dài & Ngắn Tay, Cổ Áo 3 Nút Kim Loại, Áo Thun Thời Trang",
    slug: toSlug(
      "Muscle Cmdr Men's Slim Fit Henley Shirt Long&Short Business Sleeve Casual 3 Metal Buton Placket Casual Stylish T-Shirt"
    ),
    category: "T-Shirts",
    brand: " Muscle Cmdr",
    images: ["/images/p15-1.jpg", "/images/p15-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 29.99,
    listPrice: 35.99,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 15,
    description:
      "Thiết kế Slim Fit: Áo Henley Slim Fit của Muscle Cmdr được thiết kế ôm sát cơ thể, làm nổi bật cơ bắp và tạo dáng hình thanh thoát, hoàn hảo cho mọi dịp.",
    sizes: ["XL", "XXL"],
    colors: ["Blue", "Yellow"],
    reviews: [],
  },
  {
    name: "Áo Thun Dài Tay Nam Hanes Beefy Henley",
    slug: toSlug("Hanes Mens Long Sleeve Beefy Henley Shirt"),
    category: "T-Shirts",
    brand: "Jerzees",
    images: ["/images/p16-1.jpg", "/images/p16-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 25.3,
    listPrice: 32.99,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 16,
    numSales: 56,
    description:
      "Vải cotton dày (Heathers là 60% cotton/40% polyester; Pebblestone là 75% cotton/25% polyester)",
    sizes: ["XL", "XXL"],
    colors: ["Grey", "White"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Silver Jeans Co. Jace Slim Fit Bootcut",
    slug: toSlug("Silver Jeans Co. Mens Jace Slim Fit Bootcut Jeans"),
    category: "Jeans",
    brand: "Silver Jeans Co",
    images: ["/images/p21-1.jpg", "/images/p21-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 95.34,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 54,
    numSales: 21,
    description:
      "Quần Jean Nam Silver Jeans Co. Jace Slim Fit Bootcut - Quần Jace là một mẫu quần jean hiện đại dành cho cao bồi. Quần ngồi dưới eo, ôm sát qua hông và đùi. Được hoàn thiện với phần ống quần bootcut dài 18 inch, phù hợp với dáng người thon gọn nhưng vẫn vừa vặn với ủng.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Blue", "Grey"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Levi's 505 Regular Fit (Cũng có sẵn cho Big & Tall)",
    slug: toSlug(
      "Levi's mens 505 Regular Fit Jeans (Also Available in Big & Tall)"
    ),
    category: "Jeans",
    brand: "Levi's",
    images: ["/images/p22-1.jpg", "/images/p22-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 59.99,
    listPrice: 69.99,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 22,
    numSales: 54,
    description:
      "Một chiếc quần cổ điển thực sự, 505 được thiết kế để có vẻ ngoài và phong cách thoải mái.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Blue", "Grey"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Essentials Straight-Fit Stretch",
    slug: toSlug("Essentials Mens Straight-Fit Stretch Jean"),
    category: "Jeans",
    brand: "Essentials",
    images: ["/images/p23-1.jpg", "/images/p23-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 38.9,
    listPrice: 45,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 23,
    numSales: 54,
    description:
      "Những chiếc quần jean 5 túi cổ điển này được làm từ vải có chút độ co giãn để mang lại sự thoải mái và giúp duy trì hình dáng của chúng.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Grey", "Blue"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Buffalo David Bitton Driven Relaxed Denim",
    slug: toSlug(
      "Buffalo David Bitton Mens Men's Driven Relaxed Denim JeansJeans"
    ),
    category: "Jeans",
    brand: "Buffalo David Bitton",
    images: ["/images/p24-1.jpg", "/images/p24-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 69.99,
    listPrice: 100,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 24,
    numSales: 53,
    description:
      "Quần jean denim tái chế co giãn với màu xanh wash tự nhiên và được mài. Đặc điểm gồm thắt lưng thấp thoải mái và kiểu dáng suông. Vẻ ngoài mài mòn mang lại cảm giác đã sử dụng lâu dài. Logo thân thiện với môi trường màu nâu đỏ được gắn ở thắt lưng phía sau. Hình ảnh lá phong đặc trưng được đục nổi ở khóa kéo.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Blue", "Grey"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Dickies Relaxed Fit Carpenter",
    slug: toSlug("Dickies Mens Relaxed Fit Carpenter Jean"),
    category: "Jeans",
    brand: "Dickies",
    images: ["/images/p25-1.jpg", "/images/p25-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 95.34,
    listPrice: 0,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 25,
    numSales: 48,
    description:
      "Quần jean làm việc thoải mái với các túi kiểu thợ mộc truyền thống và logo ở túi sau.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Blue", "Grey"],
    reviews: [],
  },
  {
    name: "Quần Jean Nam Wrangler Premium Performance Cowboy Cut Slim Fit",
    slug: toSlug("Wrangler mens Premium Performance Cowboy Cut Slim Fit Jean"),
    category: "Jeans",
    brand: "Wrangler",
    images: ["/images/p26-1.jpg", "/images/p26-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 81.78,
    listPrice: 149.99,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 26,
    numSales: 48,
    description:
      "Được thiết kế với độ vừa vặn chức năng, chiếc quần này được làm để mặc cùng với đôi bốt yêu thích của bạn. Được cấu tạo với dáng ôm vừa vặn ở eo, mông và đùi, chiếc quần này mang lại sự thoải mái và chức năng cho những ngày dài trên yên ngựa.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Blue", "Grey"],
    reviews: [],
  },
  {
    name: "Đồng hồ nam Seiko với mặt đồng hồ đen",
    slug: toSlug("Seiko Men's Analogue Watch with Black Dial"),
    category: "Wrist Watches",
    brand: "Seiko",
    images: ["/images/p31-1.jpg", "/images/p31-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 530.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 31,
    numSales: 48,
    description:
      "Vỏ đồng hồ: Vỏ làm bằng thép không gỉ, hình dáng vỏ: tròn, màu sắc vỏ: bạc, Kính: Hardlex, Loại khóa: Khóa gập với an toàn.",
    sizes: [],
    colors: [],
    reviews: [],
  },
  {
    name: "Đồng hồ tự động SEIKO 5 Sport SRPJ83 mặt số màu be, dây nylon, màu be",
    slug: toSlug(
      "SEIKO 5 Sport SRPJ83 Beige Dial Nylon Automatic Watch, Beige, Automatic Watch"
    ),
    category: "Wrist Watches",
    brand: "Seiko",
    images: ["/images/p32-1.jpg", "/images/p32-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 375.83,
    listPrice: 400,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 32,
    numSales: 48,
    description:
      "Bộ sưu tập Seiko 5 Sport lấy cảm hứng từ kiểu dáng cổ điển của đồng hồ trường/máy bay: Tự động với khả năng lên cót tay.",
    sizes: [],
    colors: [],
    reviews: [],
  },
  {
    name: "Đồng hồ Casio nam mặt kim loại thép không gỉ dây đeo, màu bạc, đồng hồ thể thao 42mm",
    slug: toSlug(
      "Casio Men's Heavy Duty Analog Quartz Stainless Steel Strap, Silver, 42 Casual Watch"
    ),
    category: "Wrist Watches",
    brand: "Casio",
    images: ["/images/p33-1.jpg", "/images/p33-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 60.78,
    listPrice: 0,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 33,
    numSales: 48,
    description:
      "Dòng đồng hồ Casio đang phát triển với mẫu MWA-100H-1AVEF này. Với vỏ thép không gỉ có hoàn thiện chải xước, đồng hồ sẽ dễ dàng chịu được tất cả các va đập của cuộc sống hàng ngày.",
    sizes: [],
    colors: [],
    reviews: [],
  },
  {
    name: "Đồng hồ Casio cổ điển vỏ thép không gỉ màu bạc, đồng hồ chỉ ngày",
    slug: toSlug(
      "Casio Classic Silver-Tone Stainless Steel Band Date Indicator Watch"
    ),
    category: "Wrist Watches",
    brand: "Casio",
    images: ["/images/p34-1.jpg", "/images/p34-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 34.22,
    listPrice: 54.99,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 34,
    numSales: 48,
    description:
      "Mẫu đồng hồ MTPVD01D-7EV mới có khả năng chống nước 50m, vỏ thép không gỉ và mặt đồng hồ trắng. Đồng hồ 3 kim, hiển thị ngày này là lựa chọn hoàn hảo cho mọi môi trường.",
    sizes: [],
    colors: [],
    reviews: [],
  },
  {
    name: "Đồng hồ Fossil nam Grant vỏ thép không gỉ, đồng hồ chronograph",
    slug: toSlug("Fossil Men's Grant Stainless Steel Quartz Chronograph Watch"),
    category: "Wrist Watches",
    brand: "Fossil",
    images: ["/images/p35-1.jpg", "/images/p35-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 171.22,
    listPrice: 225,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 35,
    numSales: 48,
    description:
      "Đồng hồ chronograph với vỏ màu bạc và xanh, mặt đồng hồ màu xanh ánh kim và chỉ số số La Mã màu bạc.",
    sizes: [],
    colors: ["Blue", "Black", "Sivler"],
    reviews: [],
  },
  {
    name: "Đồng hồ Fossil nam Machine vỏ thép không gỉ, đồng hồ quartz",
    slug: toSlug("Fossil Men's Machine Stainless Steel Quartz Watch"),
    category: "Wrist Watches",
    brand: "Fossil",
    images: ["/images/p36-1.jpg", "/images/p36-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 158.21,
    listPrice: 229.0,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 36,
    numSales: 49,
    description:
      "Với phong cách nam tính màu đen trên đen, đồng hồ Machine lấy cảm hứng từ công nghiệp sẽ tạo thêm điểm nhấn hiện đại cho vẻ ngoài giản dị của bạn. Đồng hồ này còn có chuyển động ba kim trên dây đeo thép không gỉ.",
    sizes: [],
    colors: ["Brown", "Silver", "Black"],
    reviews: [],
  },
  {
    name: "Giày đào tạo nam adidas Grand Court 2.0",
    slug: toSlug("adidas Mens Grand Court 2.0 Training Shoes Training Shoes"),
    category: "Shoes",
    brand: "adidas",
    images: ["/images/p41-1.jpg", "/images/p41-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 81.99,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 41,
    numSales: 48,
    description:
      "Lót giày Cloudfoam Comfort cực kỳ mềm mại và bồng bềnh, với hai lớp đệm được phủ bởi lưới mềm, thoáng khí",
    sizes: ["8", "9", "10"],
    colors: ["White", "Black", "Grey"],
    reviews: [],
  },
  {
    name: "Giày chạy bộ nam ziitop, giày thể thao thời trang, giày oxford công sở, giày thể thao nhẹ, thoáng khí",
    slug: toSlug(
      "ziitop Men's Running Walking Shoes Fashion Sneakers Mesh Dress Shoes Business Oxfords Shoes Lightweight Casual Breathable Work Formal Shoes"
    ),
    category: "Shoes",
    brand: "ziitop",
    images: ["/images/p42-1.jpg", "/images/p42-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 39.97,
    listPrice: 49.96,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 42,
    numSales: 50,
    description:
      "Lót giày Cloudfoam Comfort cực kỳ mềm mại và bồng bềnh, với hai lớp đệm được phủ bởi lưới mềm, thoáng khí",
    sizes: ["8", "9", "10"],
    colors: ["Beige", "Black", "Grey"],
    reviews: [],
  },
  {
    name: "Giày nam Skechers Summits High Range Hands Free Slip-in",
    slug: toSlug(
      "Skechers mens Summits High Range Hands Free Slip-in Shoes Work shoe"
    ),
    category: "Shoes",
    brand: "Skechers",
    images: ["/images/p43-1.jpg", "/images/p43-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 99.99,
    listPrice: 0,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 43,
    numSales: 72,
    description:
      "Bước vào sự thoải mái dễ dàng với Skechers Hands Free Slip-ins™: Summits - High Range. Cùng với Exclusive Heel Pillow™ giúp giữ chân bạn chắc chắn, kiểu dáng này có phần gót giày mô phỏng nổi Skechers Slip-ins™ và lớp vải lưới trên cùng với dây giày cố định",
    sizes: ["8", "9", "10"],
    colors: ["Blue", "Black", "Gray"],
    reviews: [],
  },
  {
    name: "Giày chạy bộ DLWKIPV nam, giày thể thao, giày đi bộ ngoài trời, giày chạy nhẹ, linh hoạt, thoải mái, thoáng khí",
    slug: toSlug(
      "DLWKIPV Mens Running Shoes Tennis Cross Training Sneakers Fashion Non Slip Outdoor Walking Jogging Shoes Mesh Light Flexible Comfortable Breathable Shoes"
    ),
    category: "Shoes",
    brand: "DLWKIPV",
    images: ["/images/p44-1.jpg", "/images/p44-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 36.99,
    listPrice: 56.9,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 44,
    numSales: 72,
    description:
      "Thiết kế: Lưới phía trên, thông thoáng. Đế chống trượt, giảm chấn và chống trượt. Bên trong giày rộng và mềm, mang đến cảm giác thoải mái",
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["Brown", "Grey", "Black"],
    reviews: [],
  },
  {
    name: "Giày chạy bộ nam ASICS GT-2000 13",
    slug: toSlug("ASICS Men's GT-2000 13 Running Shoes"),
    category: "Shoes",
    brand: "ASICS",
    images: ["/images/p45-1.jpg", "/images/p45-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 179.95,
    listPrice: 200,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 45,
    numSales: 64,
    description:
      "Ít nhất 50% vật liệu chính của giày được làm từ nguyên liệu tái chế để giảm lãng phí và khí thải carbon",
    sizes: ["8", "9", "10", "11"],
    colors: ["Blue", "Black", "Grey"],
    reviews: [],
  },
  {
    name: "Giày Wearbreeze nam, Urban - Giày siêu thoải mái, Giày Mesh thời trang cho nam",
    slug: toSlug(
      "Mens Wearbreeze Shoes, Urban - Ultra Comfortable Shoes, Breeze Shoes for Men, Men's Mesh Dress Sneakers Business Shoes"
    ),
    category: "Shoes",
    brand: "Generic",
    images: ["/images/p46-1.jpg", "/images/p46-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 32.99,
    listPrice: 80,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 46,
    numSales: 48,
    description:
      "Lót giày Cloudfoam Comfort cực kỳ mềm mại và bồng bềnh, với hai lớp đệm được phủ bởi lưới mềm, thoáng khí",
    sizes: ["8", "9", "10", "11"],
    colors: ["Green", "Black", "Grey"],
    reviews: [],
  },
];

const reviews = [
  {
    rating: 1,
    title: "Chất lượng kém",
    comment:
      "Rất thất vọng. Sản phẩm bị hỏng sau vài lần sử dụng. Không đáng tiền.",
  },
  {
    rating: 2,
    title: "Thất vọng",
    comment:
      "Không như mong đợi. Chất liệu trông rẻ tiền và không vừa vặn. Sẽ không mua lại.",
  },
  {
    rating: 2,
    title: "Cần cải thiện",
    comment:
      "Nhìn đẹp nhưng không hoạt động như mong đợi. Sẽ không giới thiệu nếu không nâng cấp.",
  },
  {
    rating: 3,
    title: "Không tệ",
    comment:
      "Sản phẩm này khá ổn, chất lượng tốt nhưng cần cải thiện một số chi tiết.",
  },
  {
    rating: 3,
    title: "Ổn, nhưng chưa xuất sắc",
    comment:
      "Nó hoạt động, nhưng không tốt như tôi mong đợi. Chất lượng trung bình và thiếu hoàn thiện.",
  },
  {
    rating: 3,
    title: "Sản phẩm tốt",
    comment:
      "Sản phẩm này rất tuyệt vời, tôi rất thích! Chất lượng hàng đầu, chất liệu thoải mái và thoáng khí.",
  },
  {
    rating: 4,
    title: "Khá tốt",
    comment:
      "Sản phẩm chắc chắn! Giá trị tốt so với giá tiền, nhưng vẫn có thể cải thiện một chút.",
  },
  {
    rating: 4,
    title: "Rất hài lòng",
    comment: "Sản phẩm tốt! Chất lượng cao và đáng giá. Sẽ cân nhắc mua lại.",
  },
  {
    rating: 4,
    title: "Hoàn toàn yêu thích!",
    comment:
      "Hoàn hảo trong mọi khía cạnh! Chất lượng, thiết kế và sự thoải mái vượt quá mong đợi của tôi.",
  },
  {
    rating: 4,
    title: "Vượt qua mong đợi!",
    comment:
      "Sản phẩm tuyệt vời! Chất lượng cao, cảm giác bền và hoạt động tốt. Rất khuyến khích!",
  },
  {
    rating: 5,
    title: "Mua hàng hoàn hảo!",
    comment:
      "Không thể hài lòng hơn với sản phẩm này. Chất lượng xuất sắc và hoạt động trơn tru!",
  },
  {
    rating: 5,
    title: "Rất khuyến khích",
    comment:
      "Sản phẩm tuyệt vời! Đáng từng đồng, thiết kế đẹp và cảm giác cao cấp. Tôi rất hài lòng.",
  },
  {
    rating: 5,
    title: "Đúng như tôi cần",
    comment:
      "Chính xác như mô tả! Chất lượng vượt xa mong đợi và giao hàng nhanh chóng.",
  },
  {
    rating: 5,
    title: "Lựa chọn xuất sắc!",
    comment:
      "Sản phẩm này thật tuyệt vời! Tất cả mọi thứ từ chất liệu đến chức năng đều cao cấp.",
  },
  {
    rating: 5,
    title: "Không thể đòi hỏi hơn!",
    comment:
      "Tôi rất yêu thích sản phẩm này! Nó bền, phong cách và hoạt động tuyệt vời. Sẽ mua lại mà không do dự.",
  },
];

const data: Data = {
  users,
  products,
  reviews,
  headerMenus: [
    {
      name: "Khuyến mãi hôm nay",
      href: "/search?tag=todays-deal",
    },
    {
      name: "Sản phẩm mới",
      href: "/search?tag=new-arrival",
    },
    {
      name: "Sản phẩm nổi bật",
      href: "/search?tag=featured",
    },
    {
      name: "Bán chạy nhất",
      href: "/search?tag=best-seller",
    },
    {
      name: "Lịch sử duyệt",
      href: "/#browsing-history",
    },
    {
      name: "Dịch vụ khách hàng",
      href: "/page/customer-service",
    },
    {
      name: "Về chúng tôi",
      href: "/page/about-us",
    },
    {
      name: "Trợ giúp",
      href: "/page/help",
    },
  ],
  carousels: [
    {
      title: "Giày Bán Chạy Nhất",
      buttonCaption: "Mua Ngay",
      image: "/images/banner3.jpg",
      url: "/search?category=Shoes",
      isPublished: true,
    },
    {
      title: "Áo Thun Bán Chạy Nhất",
      buttonCaption: "Mua Ngay",
      image: "/images/banner1.jpg",
      url: "/search?category=T-Shirts",
      isPublished: true,
    },
    {
      title: "Ưu Đãi Tốt Nhất Về Đồng Hồ Đeo Tay",
      buttonCaption: "Xem Thêm",
      image: "/images/banner2.jpg",
      url: "/search?category=Wrist Watches",
      isPublished: true,
    },
  ],
  webPages: [
    {
      title: "Về Chúng Tôi",
      slug: "ve-chung-toi",
      content: `Chào mừng bạn đến với [Tên Cửa Hàng Của Bạn], điểm đến tin cậy của bạn cho những sản phẩm chất lượng và dịch vụ tuyệt vời. Hành trình của chúng tôi bắt đầu với sứ mệnh mang lại cho bạn trải nghiệm mua sắm tốt nhất bằng cách cung cấp nhiều loại sản phẩm với giá cả cạnh tranh, tất cả trên một nền tảng tiện lợi.
Tại [Tên Cửa Hàng Của Bạn], chúng tôi ưu tiên sự hài lòng của khách hàng và sự đổi mới. Đội ngũ của chúng tôi làm việc không ngừng để tuyển chọn đa dạng các mặt hàng, từ những vật dụng thiết yếu hàng ngày đến những ưu đãi độc quyền, đảm bảo có thứ gì đó cho mọi người. Chúng tôi cũng nỗ lực để mang lại trải nghiệm mua sắm liền mạch với vận chuyển nhanh chóng, thanh toán an toàn và hỗ trợ khách hàng tuyệt vời.
Khi chúng tôi tiếp tục phát triển, cam kết của chúng tôi về chất lượng và dịch vụ vẫn không thay đổi. Cảm ơn bạn đã chọn [Tên Cửa Hàng Của Bạn]—chúng tôi mong được trở thành một phần của hành trình của bạn và mang lại giá trị trong từng bước.`,
      isPublished: true,
    },
    {
      title: "Liên Hệ",
      slug: "lien-he",
      content: `Chúng tôi luôn sẵn sàng giúp đỡ! Nếu bạn có bất kỳ câu hỏi, thắc mắc hay phản hồi nào, đừng ngần ngại liên hệ với chúng tôi. Đội ngũ của chúng tôi sẵn sàng hỗ trợ bạn và đảm bảo rằng bạn có trải nghiệm mua sắm tốt nhất.
**Hỗ Trợ Khách Hàng**
Đối với các yêu cầu về đơn hàng, sản phẩm hoặc các vấn đề liên quan đến tài khoản, hãy liên hệ với đội ngũ hỗ trợ khách hàng của chúng tôi:
- **Email:** support@example.com
- **Điện thoại:** +1 (123) 456-7890
- **Trò chuyện trực tiếp:** Có sẵn trên trang web của chúng tôi từ 9h sáng đến 6h tối (Thứ Hai đến Thứ Sáu).
**Văn Phòng Chính**
Đối với các yêu cầu liên quan đến doanh nghiệp hoặc công ty, hãy liên hệ với trụ sở chính của chúng tôi:
- **Địa chỉ:** 1234 Đường E-Commerce, Phòng 567, Thành Phố Kinh Doanh, BC 12345
- **Điện thoại:** +1 (987) 654-3210
Chúng tôi rất mong được hỗ trợ bạn! Sự hài lòng của bạn là ưu tiên của chúng tôi.
`,
      isPublished: true,
    },
    {
      title: "Trợ Giúp",
      slug: "tro-giup",
      content: `Chào mừng bạn đến với Trung Tâm Hỗ Trợ của chúng tôi! Chúng tôi ở đây để giúp bạn với bất kỳ câu hỏi hoặc thắc mắc nào khi bạn mua sắm với chúng tôi. Dù bạn cần trợ giúp về đơn hàng, quản lý tài khoản, hay yêu cầu sản phẩm, trang này cung cấp tất cả thông tin bạn cần để sử dụng nền tảng của chúng tôi một cách dễ dàng.
**Đặt Hàng và Quản Lý Đơn Hàng**
Việc đặt hàng rất đơn giản và an toàn. Duyệt qua các danh mục sản phẩm, thêm các mặt hàng vào giỏ hàng của bạn và tiến hành thanh toán. Sau khi đặt hàng, bạn có thể theo dõi tình trạng đơn hàng qua tài khoản của mình trong phần "Đơn Hàng Của Tôi". Nếu bạn cần thay đổi hoặc hủy đơn hàng, vui lòng liên hệ với chúng tôi sớm nhất để được hỗ trợ.
**Vận Chuyển và Hoàn Trả**
Chúng tôi cung cấp nhiều tùy chọn vận chuyển để phù hợp với nhu cầu của bạn, bao gồm giao hàng tiêu chuẩn và giao hàng nhanh. Để biết chi tiết về chi phí vận chuyển và thời gian giao hàng, vui lòng truy cập trang Chính Sách Vận Chuyển của chúng tôi. Nếu bạn không hài lòng với sản phẩm, quy trình hoàn trả của chúng tôi rất đơn giản và cho phép bạn yêu cầu hoàn trả trong thời hạn đã quy định. Vui lòng xem thêm tại Chính Sách Hoàn Trả của chúng tôi.
**Tài Khoản và Hỗ Trợ**
Việc quản lý tài khoản của bạn rất dễ dàng. Đăng nhập để cập nhật thông tin cá nhân, phương thức thanh toán và địa chỉ lưu trữ. Nếu bạn gặp phải vấn đề hoặc cần hỗ trợ thêm, đội ngũ hỗ trợ khách hàng của chúng tôi luôn sẵn sàng qua email, trò chuyện trực tiếp hoặc điện thoại. Hãy truy cập trang Liên Hệ của chúng tôi để biết thêm thông tin hỗ trợ.`,
      isPublished: true,
    },
    {
      title: "Chính Sách Bảo Mật",
      slug: "chinh-sach-bao-mat",
      content: `Chúng tôi coi trọng sự riêng tư của bạn và cam kết bảo vệ thông tin cá nhân của bạn. Thông báo Bảo Mật này giải thích cách chúng tôi thu thập, sử dụng và chia sẻ dữ liệu của bạn khi bạn tương tác với các dịch vụ của chúng tôi. Bằng việc sử dụng nền tảng của chúng tôi, bạn đồng ý với các thực hành được mô tả trong đây.
Chúng tôi thu thập các dữ liệu như tên, địa chỉ email, và thông tin thanh toán của bạn để cung cấp cho bạn các dịch vụ được cá nhân hóa và cải thiện trải nghiệm của bạn. Thông tin này cũng có thể được sử dụng cho các mục đích tiếp thị, nhưng chỉ khi bạn đồng ý. Ngoài ra, chúng tôi có thể chia sẻ dữ liệu của bạn với các nhà cung cấp thứ ba tin cậy để thực hiện các giao dịch hoặc giao hàng.
Dữ liệu của bạn được bảo vệ thông qua các biện pháp bảo mật mạnh mẽ để ngăn chặn truy cập trái phép. Tuy nhiên, bạn có quyền truy cập, chỉnh sửa hoặc xóa thông tin cá nhân của mình bất kỳ lúc nào. Nếu bạn có thắc mắc hoặc lo ngại về sự riêng tư của mình, hãy liên hệ với đội ngũ hỗ trợ của chúng tôi.`,
      isPublished: true,
    },
    {
      title: "Điều Kiện Sử Dụng",
      slug: "dieu-kien-su-dung",
      content: `Chào mừng đến với [Tên Trang Thương Mại Điện Tử]. Bằng việc truy cập hoặc sử dụng trang web của chúng tôi, bạn đồng ý tuân thủ và bị ràng buộc bởi các điều khoản và điều kiện sau đây. Những điều khoản này quy định việc sử dụng nền tảng của chúng tôi, bao gồm việc duyệt web, mua sản phẩm và tương tác với bất kỳ nội dung hay dịch vụ nào được cung cấp. Bạn phải từ 18 tuổi trở lên hoặc có sự đồng ý của cha mẹ hoặc người giám hộ để sử dụng trang web này. Bất kỳ vi phạm nào đối với các điều khoản này có thể dẫn đến việc chấm dứt quyền truy cập của bạn vào nền tảng của chúng tôi.
Chúng tôi cố gắng đảm bảo tất cả các mô tả sản phẩm, giá cả và thông tin về tình trạng sẵn có trên trang web của mình là chính xác. Tuy nhiên, sai sót có thể xảy ra và chúng tôi có quyền sửa chữa chúng mà không cần thông báo trước. Tất cả các giao dịch mua hàng đều phải tuân theo chính sách hoàn trả và hoàn tiền của chúng tôi. Bằng cách sử dụng trang web của chúng tôi, bạn công nhận rằng thông tin cá nhân của bạn sẽ được xử lý theo chính sách bảo mật của chúng tôi, đảm bảo rằng dữ liệu của bạn được xử lý một cách an toàn và có trách nhiệm. Vui lòng xem xét kỹ các điều khoản này trước khi tiến hành bất kỳ giao dịch nào.`,
      isPublished: true,
    },
    {
      title: "Dịch Vụ Khách Hàng",
      slug: "dich-vu-khach-hang",
      content: `Tại [Tên Cửa Hàng Của Bạn], đội ngũ dịch vụ khách hàng của chúng tôi ở đây để đảm bảo rằng bạn có trải nghiệm mua sắm tốt nhất. Dù bạn cần trợ giúp về đơn hàng, chi tiết sản phẩm hay hoàn trả, chúng tôi cam kết cung cấp sự hỗ trợ nhanh chóng và hữu ích.
Nếu bạn có bất kỳ câu hỏi hoặc thắc mắc nào, vui lòng liên hệ với chúng tôi qua các phương thức liên lạc sau:
- **Email:** support@example.com
- **Điện thoại:** +1 (123) 456-7890
- **Trò chuyện trực tiếp:** Có sẵn trên trang web của chúng tôi để hỗ trợ ngay lập tức
Chúng tôi cũng cung cấp các tài nguyên hữu ích như theo dõi đơn hàng, hướng dẫn sản phẩm và các câu hỏi thường gặp để giúp bạn với những thắc mắc phổ biến. Sự hài lòng của bạn là ưu tiên hàng đầu của chúng tôi và chúng tôi ở đây để giải quyết mọi vấn đề một cách nhanh chóng và hiệu quả. Cảm ơn bạn đã chọn chúng tôi!`,
      isPublished: true,
    },
  ],
};

export default data;
